name: Docker Image CI

on:
  workflow_dispatch:
  
jobs:
  build_multiarch:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out Keycloak-Containers
        uses: actions/checkout@master
        with:
          repository: keycloak/keycloak-containers
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Get Latest Release
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: keycloak
          repo: keycloak-containers
          
      - name: test print
        run: |
          echo ${{ steps.latest_version.outputs.latest_tag }},
          echo ${{ steps.latest_version.outputs.latest_tag_published_at }}
        
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=raw,{{sha}}
          
      - name: build & push image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./server/Dockerfile
          context: ./server/
          tags: |
            tags: ${{ steps.meta.outputs.tags }}
