name: testbuild keycloak

on:
  workflow_dispatch:

jobs:
  build_multiarch:
    runs-on: ubuntu-latest
    steps:
      
      - name: Check out Keycloak-Containers
        uses: actions/checkout@master
        with:
          repository: keycloak/keycloak-containers
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      - name: build & push image (docker-keycloak:latest)
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: ./server/Dockerfile
          context: ./server/
          tags: |
            ghcr.io/opencirklepkgs/docker-keycloak:latest
